### ISSUE TITLE
requesting user manual 

### ISSUE THREAD

**Issue by LeCommonMan** [Hyperion101010/naukri-scraper#1]
trying to run this, but its not resulting in any action or result. 
( python 2.7, dependencies BeautifulSoup & requests are already installed )

can you please include a elaborated guide.

**Comment by maneeshsandra** [comment]
upgrade to python 3+

**Comment by Hyperion101010** [comment]
Yeah it uses python3 , python 2.7 is not in active development.
Apologies from my side as well cause i should have added backwards compatible code.

**Comment by Hyperion101010** [comment]
Closing this issue as it seems problem is solved.
