### ISSUE TITLE
We can do this better if you respond

### ISSUE THREAD

**Issue by maneeshsandra** [Hyperion101010/naukri-scraper#2]
instead of fetching all data which is time consuming process.
we can take the parameters first like location/qualification/experience/etc then fetch the jobs.

**Comment by Hyperion101010** [comment]
Absolutely, well i developed this as a tool for a hackathon. So at that time my goal was to make it for fetching few restricted jobs. What you are suggesting is possible and will be useful for others as well.You can go ahead with the changes I am not working actively on its development.
Sorry for being late, I am nowadays working through my mentorship at Linux so I forget to check my github. Open a PR and let me know, I will check and merge it.

**Comment by Hyperion101010** [comment]
Haven't heard back will close this issue after sometime @maneeshsandra.
